title: "Rajshekhar V Bhat"
author: "Blog Author"
description: "IIT Dharwad"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "rajshekharCV.pdf", title: "CV"} 
  - {file: "publications.md", title: "Publications"}
  - {file: "/rajshekharCV.pdf", title: "Projects"}
  - {file: "/rajshekharCV.pdf", title: "Courses"}
  - {file: "/rajshekharCV.pdf", title: "Students"}

  
 
# - {file: "index.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rajshekhar.bhat@iitdh.ac.in"}
  - {title: Google Scholar, url: "https://scholar.google.com/citations?user=o2ZFG84AAAAJ&hl=en"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
